default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dice_development

test:
  <<: *default
  database: dice_test


production:
  <<: *default
  database: dice_production
  username: dice
  password: <%= ENV["DICE_DATABASE_PASSWORD"] %>
